INDICATOR_GUIDES = [
    {
        "name": "MA均线",
        "summary": "移动平均线是过去N天收盘价的平均值,反映股价趋势方向。MA5>MA10>MA20称为多头排列,代表上升趋势。",
        "formula": "MA(N) = 过去N天收盘价之和 / N",
        "buy_pattern": "MA5上穿MA10(金叉),且MA20在下方支撑",
        "sell_pattern": "MA5下穿MA10(死叉),且股价跌破MA20",
        "trap": "震荡市中均线频繁交叉,容易产生假信号",
        "weight_in_system": "多头排列在技术面评分中占10分(满分40)",
    },
    {
        "name": "MACD",
        "summary": "MACD由DIF(快线)和DEA(慢线)组成。当DIF从下往上穿越DEA叫金叉,是买入信号;反之叫死叉,是卖出信号。",
        "formula": "DIF = EMA12 - EMA26, DEA = DIF的9日EMA",
        "buy_pattern": "DIF上穿DEA形成金叉,尤其在零轴附近的金叉最有价值",
        "sell_pattern": "DIF下穿DEA形成死叉",
        "trap": "MACD是滞后指标,快速行情中信号会延迟",
        "weight_in_system": "MACD金叉在技术面评分中占8分(满分40)",
    },
    {
        "name": "KDJ",
        "summary": "KDJ是超买超卖指标。K值在20以下是超卖区,80以上是超买区。K线上穿D线是金叉。",
        "formula": "RSV = (收盘-N日最低)/(N日最高-N日最低)×100",
        "buy_pattern": "K在20-50区间上穿D线",
        "sell_pattern": "K在80以上下穿D线",
        "trap": "强势上涨中KDJ会长时间停留在超买区",
        "weight_in_system": "KDJ金叉在技术面评分中占5分(满分40)",
    },
    {
        "name": "RSI",
        "summary": "相对强弱指数,衡量买方和卖方力量对比。RSI>70超买,RSI<30超卖。",
        "formula": "RSI = 100 - 100/(1+平均涨幅/平均跌幅)",
        "buy_pattern": "RSI从30以下回升到50以上",
        "sell_pattern": "RSI从70以上回落到50以下",
        "trap": "单独使用RSI容易过早入场或离场",
        "weight_in_system": "RSI作为辅助参考,不单独计分",
    },
    {
        "name": "布林带",
        "summary": "布林带由中轨(20日均线)和上下轨(±2倍标准差)组成。股价在上下轨之间波动。",
        "formula": "中轨=MA20, 上轨=MA20+2×STD20, 下轨=MA20-2×STD20",
        "buy_pattern": "股价突破中轨向上轨运行",
        "sell_pattern": "股价从上轨回落跌破中轨",
        "trap": "极端行情中股价可以沿着上轨或下轨运行很久",
        "weight_in_system": "布林带位置在技术面评分中占7分(满分40)",
    },
    {
        "name": "成交量",
        "summary": "成交量是市场参与度的体现。放量上涨代表买方力量强,缩量下跌说明卖压减轻。",
        "formula": "量比 = 今日成交量/过去20日平均成交量",
        "buy_pattern": "股价上涨伴随成交量放大(量比>1.5)",
        "sell_pattern": "股价上涨但成交量萎缩(量价背离)",
        "trap": "放量不代表一定上涨,也可能是主力出货",
        "weight_in_system": "成交量放大在技术面评分中占5分(满分40)",
    },
    {
        "name": "量比",
        "summary": "量比反映当天交易活跃度相对于近期平均水平。量比>1.5说明交易明显放大。",
        "formula": "量比 = 当日成交量/过去5日平均成交量",
        "buy_pattern": "量比1.5-5之间,配合股价上涨",
        "sell_pattern": "量比突然放大到5以上,可能是拉高出货",
        "trap": "开盘时量比波动大,不具参考价值",
        "weight_in_system": "量比在资金面评分中占5分(满分30)",
    },
    {
        "name": "北向资金",
        "summary": "北向资金是通过沪港通/深港通流入A股的外资,被称为聪明钱。",
        "formula": "北向净流入 = 买入金额 - 卖出金额",
        "buy_pattern": "连续3天以上净流入,总额超过50亿",
        "sell_pattern": "持续大额净流出",
        "trap": "单日大额买入可能是被动基金调仓",
        "weight_in_system": "北向资金在资金面评分中占10分(满分30)",
    },
    {
        "name": "主力资金流",
        "summary": "通过分析大单和小单的买卖方向,判断主力资金态度。",
        "formula": "主力净流入 = 超大单买入+大单买入-超大单卖出-大单卖出",
        "buy_pattern": "主力资金持续净流入,散户净流出",
        "sell_pattern": "主力资金大幅净流出",
        "trap": "资金流数据有延迟且算法各平台不同",
        "weight_in_system": "主力资金在资金面评分中占10分(满分30)",
    },
    {
        "name": "板块轮动",
        "summary": "A股有明显的板块轮动特征,跟踪板块热度有助于选股。",
        "formula": "板块热度 = 板块涨幅排名百分位 + 板块资金净流入排名",
        "buy_pattern": "板块开始放量上涨,多只个股涨停",
        "sell_pattern": "板块连续上涨多日,出现冲高回落",
        "trap": "追板块尾部容易被套",
        "weight_in_system": "板块热度在情绪面评分中占5分(满分10)",
    },
]
